// ------------
// enumerations
// ------------

#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_topology_sort>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_renderer_type>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_access>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_occlusion_query_result>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_attrib>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_topology>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_topology_convert>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_view_mode>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_backbuffer_ratio>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_render_frame>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_attrib_type>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_function_id>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_texture_format>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_uniform_type>());
#endif
#ifdef GLOBAL_NAMESPACE
addEnumeration(make_smart<Enumerationbgfx_fatal>());
#endif

