// ------------
// structures
// ------------

#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_texture_handle_s = make_smart<bgfx_texture_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_texture_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_resolution_s = make_smart<bgfx_resolution_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_resolution_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_memory_s = make_smart<bgfx_memory_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_memory_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_uniform_handle_s = make_smart<bgfx_uniform_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_uniform_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_caps_limits_s = make_smart<bgfx_caps_limits_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_caps_limits_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_shader_handle_s = make_smart<bgfx_shader_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_shader_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_uniform_info_s = make_smart<bgfx_uniform_info_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_uniform_info_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_transient_vertex_buffer_s = make_smart<bgfx_transient_vertex_buffer_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_transient_vertex_buffer_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_attachment_s = make_smart<bgfx_attachment_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_attachment_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_vertex_buffer_handle_s = make_smart<bgfx_vertex_buffer_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_vertex_buffer_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_view_stats_s = make_smart<bgfx_view_stats_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_view_stats_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_index_buffer_handle_s = make_smart<bgfx_index_buffer_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_index_buffer_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_indirect_buffer_handle_s = make_smart<bgfx_indirect_buffer_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_indirect_buffer_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_vertex_layout_handle_s = make_smart<bgfx_vertex_layout_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_vertex_layout_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_allocator_vtbl_s = make_smart<bgfx_allocator_vtbl_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_allocator_vtbl_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_internal_data_s = make_smart<bgfx_internal_data_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_internal_data_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_transient_index_buffer_s = make_smart<bgfx_transient_index_buffer_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_transient_index_buffer_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_instance_data_buffer_s = make_smart<bgfx_instance_data_buffer_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_instance_data_buffer_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_encoder_stats_s = make_smart<bgfx_encoder_stats_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_encoder_stats_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_init_limits_s = make_smart<bgfx_init_limits_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_init_limits_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_stats_s = make_smart<bgfx_stats_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_stats_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_vertex_layout_s = make_smart<bgfx_vertex_layout_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_vertex_layout_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_init_s = make_smart<bgfx_init_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_init_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_program_handle_s = make_smart<bgfx_program_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_program_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_transform_s = make_smart<bgfx_transform_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_transform_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_allocator_interface_s = make_smart<bgfx_allocator_interface_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_allocator_interface_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_dynamic_vertex_buffer_handle_s = make_smart<bgfx_dynamic_vertex_buffer_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_dynamic_vertex_buffer_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_platform_data_s = make_smart<bgfx_platform_data_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_platform_data_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_caps_gpu_s = make_smart<bgfx_caps_gpu_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_caps_gpu_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_frame_buffer_handle_s = make_smart<bgfx_frame_buffer_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_frame_buffer_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_dynamic_index_buffer_handle_s = make_smart<bgfx_dynamic_index_buffer_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_dynamic_index_buffer_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_occlusion_query_handle_s = make_smart<bgfx_occlusion_query_handle_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_occlusion_query_handle_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_texture_info_s = make_smart<bgfx_texture_info_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_texture_info_s);
#endif
#ifdef GLOBAL_NAMESPACE
auto ann_bgfx_caps_s = make_smart<bgfx_caps_s_GeneratedAnnotation>(lib);
addAnnotation(ann_bgfx_caps_s);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_texture_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_resolution_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_memory_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_uniform_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_caps_limits_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_shader_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_uniform_info_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_transient_vertex_buffer_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_attachment_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_vertex_buffer_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_view_stats_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_index_buffer_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_indirect_buffer_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_vertex_layout_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_allocator_vtbl_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_internal_data_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_transient_index_buffer_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_instance_data_buffer_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_encoder_stats_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_init_limits_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_stats_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_vertex_layout_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_init_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_program_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_transform_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_allocator_interface_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_dynamic_vertex_buffer_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_platform_data_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_caps_gpu_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_frame_buffer_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_dynamic_index_buffer_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_occlusion_query_handle_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_texture_info_s,lib);
#endif
#ifdef GLOBAL_NAMESPACE
initRecAnnotation(ann_bgfx_caps_s,lib);
#endif

